server:
  port: 8888
# 指定静态资源路径
spring:
  resources:
    static-locations: classpath:/static/,classpath:/templates/
  mvc:
    view:
      suffix: .html
      prefix: /

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.ykcm.cc:10033/ykcm?characterEncoding=UTF-8&useSSL=false
    username: ykcm
    password: liuxin86

logging:
  level:
    cc.ykcm.dao: debug